Repository mitodl/release-script, pull requests merged in 2021-07, with the labels that each got.

#341 add the none packaging type
  constants.py
  release_test.py
  version.py
  version_test.py
Labels: Needs review

#343 add ocw-hugo-projects
  repos_info.json
Labels: work in progress

#344 Strip newline when reading version
  version.py
  version_test.py
Labels: Waiting on Author
